config/routes.rb
Playgrounds::Application.routes.draw do
  resources :playgrounds do
   collection {
    get 'update_house_status'
    get 'authenticate_house_registration'
    get 'update_spam'
    get :autocomplete_playground_address
   
  }
 
  end

get 'signout', to: 'sessions#destroy', as: 'signout'
   
get  '/playgrounds/:id/spam'  =>  "playgrounds#spam"
get  '/playgrounds/:id/show'  =>  "playgrounds#show_on_map"
match 'admin' => 'playgrounds#admin', as: :admin, via: [:get, :post]

devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  
root to: 'playgrounds#index'








  

end

app/models/playground.rb
class Playground < ActiveRecord::Base
  belongs_to :user
# attr_accessible :image, :image1

  #include Tire::Model::Search
  #include Tire::Model::Callbacks

  # mapping do
  #   indexes :id, type: 'integer'
  #   indexes :name
  #   indexes :address
  #   indexes :address_bar_index
  #   indexes :status_id
  #   indexes :user_id
  # end

# mount_uploader :image, ImageUploader
# mount_uploader :image1, ImageUploader
  # SPORTS = ['Football','Cricket','Field Hockey','Tennis','Volleyball','Table Tennis','Baseball','Golf','American Football']

  acts_as_gmappable :process_geocoding => false
  
  #validates_inclusion_of :sport, :in => Playground::SPORTS
  validates_presence_of :name
  validates_presence_of :address
  

has_attached_file :logo, :styles => {:small => "21x21", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
:url => "/system/:attachment/:id/:style/:filename"
 validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

has_attached_file :picture, :styles => {:small => "21x21", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
:url => "/system/:attachment/:id/:style/:filename"
 validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  


  # *** Server-side reverse geocoding, not for this example!
  #reverse_geocoded_by :latitude, :longitude do |obj,results|
  #  if geo = results.first
  #    obj.city    = geo.city
  #    obj.postal_code = geo.postal_code
  #    obj.country = geo.country_code
  #    obj.route = geo.address
  #  end
  #end
    
  #after_validation :reverse_geocode  

  #def address=(address)
  #end

  # def self.search(query, user_id = nil)
  #   query = query.gsub(/[^0-9A-Za-z]/, ' ')
  #   es_results = tire.search(load: true) do
  #     size 1000
  #     query do
  #       boolean do
  #         must {match :user_id, user_id} if query.present? and user_id.present?
  #         must {string ("*#{query}*"), fields: [:name, :address, :address_bar_index]} if query.present?
  #       end
  #     end
  #   end
  #   es_results.results
  # end

  def self.search(query, user_id = nil)
    playgrounds = Playground.where('LOWER(address) LIKE ? OR LOWER(address_bar_index) LIKE ?', "%#{query.downcase}%", "%#{query.downcase}%").order(:address)
    playgrounds = playgrounds.where(user_id: user_id) if user_id.present?
    return playgrounds
  end
    
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  require 'jwt/json'
  autocomplete :playground, :address, :full => false, :extra_data => [:latitude, :longitude, :myadd_type]

  before_action :authenticate_user!, only: [:admin]
  before_action :set_playground, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # before_action :authenticate_house_registration, only: [:create]
  
  respond_to :html
  
  # 404
  rescue_from ActiveRecord::RecordNotFound do |exception| 
    rescue_record_not_found(exception)
  end

  # GET /playgrounds
  # GET /playgrounds.json
  def index
    @playground = Playground.new
    if params[:id]
      puts"ASSSSSSS"
    else
      
    @playgrounds = Playground.where(:status_id =>true)
    @json = @playgrounds.to_gmaps4rails do |playground, marker|
      @playground = playground
      marker.infowindow render_to_string(:action => 'show', :layout => false)    
      marker.json({ :id => @playground.id })
    end
   end
  end

  # GET /playgrounds/1
  # GET /playgrounds/1.json
  def show
    respond_with(@playground, :layout =>  !request.xhr?)
  end

  def show_on_map
    @playground = Playground.find(params[:id])
     render layout: false
  end

  def spam
     @playground = Playground.new
     respond_with(@playground, :layout =>  !request.xhr?)
  end

  # GET /playgrounds/new
  def new
    @playground = Playground.new(params[:playground].present? ? playground_params : nil)
    respond_with(@playground, :layout => !request.xhr?)
  end

  # GET /playgrounds/1/edit
  def edit
    @playground = Playground.find(params[:id])
     render layout: false
    # respond_to do |format|
    #   format.js {}
    #   format.html {}
    # end
  end

  # POST /playgrounds
  # POST /playgrounds.json
  def create
   

   
    @playground = Playground.new(playground_params)
    if params[:home_type] && params[:home_type]=="House"
      @playground.myadd_type_id=1
      @playground.myadd_type="House"
    elsif params[:home_type] && params[:home_type]=="Apartment"
      @playground.myadd_type_id=2
      @playground.myadd_type="Apartment"
    elsif params[:home_type] && params[:home_type]=="Building"
      @playground.myadd_type_id=3
      @playground.myadd_type="Building"
    end
    address = params[:playground][:address]
    # home_type    = params[:playground][:home_type]
    # picture = params[:playground][:picture]
    country = params[:playground][:country][0..1].upcase
    state = params[:playground][:state][0..1].upcase
    city = params[:playground][:city][0..1].upcase
    postal = params[:playground][:postal_code].split('').last(2).join('')
    unicode = ([*('0'..'9')]).sample(4).join
    code = [postal,unicode].join('') 
    address_bar = [country,state,city,code].join('-')

    @playground.address_bar_index = address_bar
    @playground.user_id = current_user.id
    respond_to do |format|
      if @playground.save
        format.html { redirect_to :back, notice: 'Playground was successfully created.' }
        format.js {}
      else
        format.html { render action: 'new' }
        format.js {}      
      end
    end
 
  end

  # PATCH/PUT /playgrounds/1
  # PATCH/PUT /playgrounds/1.json
  def update

     @playground = Playground.find(params[:id])
    respond_to do |format|
      if @playground.update(playground_params)
          if params[:home_type] && params[:home_type]=="house"
          @playground.update(:myadd_type_id=>1)
          elsif params[:home_type] && params[:home_type]=="apartment"
          @playground.update(:myadd_type_id=>2)
          elsif params[:home_type] && params[:home_type]=="building"
          @playground.update(:myadd_type_id=>3)
          end

        format.html { redirect_to :back, notice: 'Playground was successfully updated.' }
        format.js {}  
      else
        format.html { render action: 'edit' }
        format.js {}  
      end
    end
  end

  # DELETE /playgrounds/1
  # DELETE /playgrounds/1.json
  def destroy
    user = User.find_by(:email => "admin@myadd.com")
    
    if (user.id != @playground.user_id)
      u = User.find(@playground.user_id) if @playground && @playground.user_id
      if !u.nil?
          u.delete
      end
    end
    @playground.delete

    respond_to do |format|
      format.html { redirect_to playgrounds_url }
      format.js {}  
    end
  end

  def admin
    unless current_user.admin?
      return redirect_to root_path, notice: "You are not authorized to perform this action"
    end
   
    @pending_playgrounds = Playground.where(:status_id => nil).paginate(page: params[:page], per_page: 3)
    @activated_playgrounds = Playground.where(:status_id => 1).paginate(page: params[:page], per_page: 3)
    @deleted_playgrounds = Playground.where(:status_id => 0).paginate(page: params[:page], per_page: 3)
  end

  def update_house_status
    if params[:id]
       playground =  Playground.find(params[:id])
       playground.update(:status_id => params[:status].to_s == "true" ? 1 : 0)
    end
 
  end
 def authenticate_house_registration

# render :format => :js
  end

  def update_spam

    @playground = Playground.find(params[:playground_id].to_i)
    @playground.update(:is_spam =>true, :spam_details => params[:spam_desc])
    render :nothing => true, :status => 200, :content_type => 'text/html'
    # if  @playground.save
    #   redirect_to :back
    # else
    #   puts 'error'
    # end
  end

  def autocomplete_playground_address
    
    term = params[:term]
    # address_bar_index = params[:address_bar_index]
    playgrounds = Playground.search(term, current_user.try(:id)) #Playground.where('LOWER(address) LIKE ? OR LOWER(address_bar_index) LIKE ?', "%#{term.downcase}%", "%#{term.downcase}%").order(:address)
    
    render :json => playgrounds.map { |playground| 
      { :latitude => playground.latitude,
        :longitude => playground.longitude,
        :myadd_type => playground.myadd_type,
        :id => playground.id,
        :label => playground.address.to_s + " - #{playground.address.similar(term).round(3)}%",
        :value => playground.address.to_s + " - #{playground.address.similar(term).round(2)}%",
        :owner => playground.user_id == current_user.try(:id)
      }
    }
   
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_playground
    @playground = Playground.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def playground_params
    params.require(:playground).permit(:name, :address, :latitude, :longitude, :street_number, :route, :city, :country, :postal_code, :state, :address_bar_index, :myadd_type_id, :hint, :user_id, :myadd_added_date, :myadd_approved_date, :status_id, :is_spam, :created_by, :last_updated_by, :image,:image1, :logo, :picture, :role)
  end
  
  # Generic not found action
  def rescue_record_not_found(exception)
    respond_to do |format|
      format.html
      format.js { render :template => "playgrounds/404.js.erb", :locals => {:exception => exception} }
    end
  end

  
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/views/playgrounds/404.js.erb
<% if params[:id] %>
    // Clear the marker itself
    clearMarkerById(<%=params[:id]%>);
    alert_user("<%= j(raw(exception.message)) %>. I'd better remove that...", "alert-error");
<%else%>  
    // notify user
    alert_user("<%= j(raw(exception.message)) %>", "alert-error");
<%end%>

// Close infowindow
closeInfowindow();

app/views/playgrounds/_create_side.html.erb
<h2>A newly created place</h2>

<div id="alert_placeholder"></div>    

<p>You can now edit or destroy the new marker by <strong>clicking on it</strong></p>
<p>The same can be said on existing markers, though their behaviour comes from the server</p>

app/views/playgrounds/_edit_form.html.erb
<%= form_for @playground, :html => { :id => 'playground_form', :multipart=>true }, :remote => true do |f| %>

  <% if @playground.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playground.errors.count, "error") %> prohibited this playground from being saved:</h2>

      <ul>
      <% @playground.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="modal-content pop2">
    <div class="modal-body">
    <table class="table table-bordered">
      <tbody>
         <tr>
          <th scope="row">Type</th>
          <%if @playground.myadd_type_id == 1  %>
          <%=address_type = "House"%>
          <% elsif @playground.myadd_type_id == 2 %>
          <%=address_type = "Apartment" %>
          <% elsif @playground.myadd_type_id == 3 %>
          <%=address_type = "Building" %>
          <% end %>
          <td><%= f.text_field :myadd_type, :class=>"form-control", :readonly => true, :value => address_type %></td>
         
        </tr>
        <tr>
          <th scope="row">Name/no</th>
          <td><%= f.text_field :name, :class=>"form-control", :value => @playground.name %></td>
        </tr>
        <tr>
          <th scope="row">Address</th>
          <td><%= text_area(:playground, :address, cols: 35, rows: 3, value: @playground.address) %></td>
        </tr> 
        <tr>
          <th scope="row">City</th>
          <td><%= f.text_field :city, :class=>"form-control", :readonly => true, :value => @playground.city %></td>
         </tr>
          <tr>
          <th scope="row">Pincode</th>
          <td><%= f.text_field :postal_code, :class=>"form-control", :readonly => true, :value => @playground.postal_code %></td>
         </tr>
          <tr>
          <th scope="row">State</th>
          <td><%= f.text_field :state, :class=>"form-control", :readonly => true, :value => @playground.state %></td>
         </tr>
          <tr>
          <th scope="row">Country</th>
          <td><%= f.text_field :country, :class=>"form-control", :readonly => true, :value => @playground.country %></td>
         </tr>
         <tr>
          <th>Photo1</th>
          <td><%= f.file_field :logo %></td>
         </tr>
         <tr>
          <th>Photo2</th>
          <td><%= f.file_field :picture %></td>
         </tr>
      </tbody>
    </table>
     <!-- <p align="center"><a href="javascript:void(0);" class="btn btn-success" onclick="start_store();">update address</a></p> -->
  
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <%= f.hidden_field :street_number %>
  <%= f.hidden_field :route %>

  <%= f.submit class: "btn btn-lg btn-primary", :value=>"update address", :style=> "height: 30px; font-size: 15px; border-radius: 1px; padding: 4px;" %>
    </div>
  </div>
  
<% end %>

app/views/playgrounds/_home_side.html.erb
<h2>Hey user!</h2>

<div id="alert_placeholder"></div>    

<p>Welcome to this <em>gmaps4rails <strong>CRUD</strong> demo</em></p>     

<p>Please allow the browser to send your location</p>     

<p><strong>Double click</strong> over the map and a form will popup to create a new place.</p>
<p>If you have opened a create form you can still dissmiss the form by clicking on close. The 
    same happens when double clicking over a different spot</p>
<p>You can also <strong>click on an existing spot</strong> to delete or modify it</p>

app/views/playgrounds/admin.html.erb
<!DOCTYPE html>
<html>
<head>
   <link href="bootstrap.css" rel="stylesheet">
   <%= stylesheet_link_tag "application", :media => "all" %>
   <!-- <link rel="stylesheet" type="text/css" href="anytime.css" /> -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script src="js/bootstrap.min.js"></script>
   
</head>
<body>

 <div class="col-md-12">
 <h3>Administration</h3>



            <div class="panel with-nav-tabs panel-primary">

                <div class="panel-heading">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1primary" data-toggle="tab">Pending</a></li>
                            <li><a href="#tab2primary" data-toggle="tab">Activated</a></li>
                            <li><a href="#tab3primary" data-toggle="tab">Deleted</a></li>
                            
                        </ul>
                </div>

<div class="panel-body">
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab1primary">

        	<h4><%= "Pending" %></h4>
<table class="table table-bordered">
<thead>
<tr>
<th><%='Address Bar'%></th>
<th><%='Name'%></th>
 <th><%='Address'%></th>
 <th><%='Type' %></th>
 <th><%='Decision'%></th>
</tr>
</thead>

<% @pending_playgrounds.each do | playground| %>
<tr>
    <td><a href="/playgrounds/<%=playground.id%>/show" id="admin_box" onclick="showMarker(<%= playground.to_json %>)"><%=playground.address_bar_index%></a></td>
    <td><%= playground.name.capitalize %></td>
    <td><%=playground.address %></td>
    <%if playground.myadd_type_id == 1  %>
    <td><%="House"%></td>
    <% elsif playground.myadd_type_id == 2 %>
    <td><%="Apartment"%></td>
    <% elsif playground.myadd_type_id == 3 %>
    <td><%="Building"%></td>
    <% else %>
    <td>&nbsp;</td>
    <% end %>
	<td>
    <a href="javascript:void(0);" onclick="update_house('<%=playground.id%>',true);" title=""><%= "Activate" %></a>
    |
    <a href="/playgrounds/<%=playground.id%>/edit" title=""><%='Edit'%></a>
    |
    <a href="javascript:void(0);" onclick="update_house('<%=playground.id%>',false);" title=""><%= "Delete" %></a>
    </td>
	</tr>
<% end %>
</table>
<%= will_paginate @pending_playgrounds %>

    </div>

    
    <div class="tab-pane fade" id="tab2primary">
                    <h4><%= "Activated" %></h4>
<table class="table table-bordered">
<thead>
<tr>
<th><%='Address Bar'%></th>
<th><%='Name'%></th>
 <th><%='Address'%></th>
 <th><%='Type' %></th>
 <th><%='Decision'%></th>
</tr>
</thead>

<% @activated_playgrounds.each do | playground| %>
<tr>
     <td><%=playground.address_bar_index %></td>
    <td><%= playground.name.capitalize %></td>
    <td><%=playground.address %></td>
    <%if playground.myadd_type_id == 1  %>
    <td><%="House"%></td>
    <% elsif playground.myadd_type_id == 2 %>
    <td><%="Apartment"%></td>
    <% elsif playground.myadd_type_id == 3 %>
    <td><%="Building"%></td>
    <% else %>
    <td>&nbsp;</td>
    <% end %>
    <td>
    <span title=""><%='Activate'%></span>
    |
    <a href="/playgrounds/<%=playground.id%>/edit" title=""><%='Edit'%></a>
    |
    <a href="javascript:void(0);" onclick="update_house('<%=playground.id%>',false);" title=""><%= "Delete" %></a>
    </td>
    
    </tr>
<% end %>
</table>
 <%= will_paginate @activated_playgrounds %>
    </div>
    <div class="tab-pane fade" id="tab3primary">
    	<h4><%= "Deleted" %></h4>
<table class="table table-bordered">
<thead>
<tr>
<th><%='Address Bar'%></th>
<th><%='Name'%></th>
 <th><%='Address'%></th>
 <th><%='Type' %></th>
 <th><%='Decision'%></th>
</tr>
</thead>

<% @deleted_playgrounds.each do | playground| %>
<tr>
     <td><%=playground.address_bar_index %></td>
    <td><%= playground.name.capitalize %></td>
    <td><%=playground.address %></td>
    <%if playground.myadd_type_id == 1  %>
    <td><%="House"%></td>
    <% elsif playground.myadd_type_id == 2 %>
    <td><%="Apartment"%></td>
    <% elsif playground.myadd_type_id == 3 %>
    <td><%="Building"%></td>
    <% else %>
    <td>&nbsp;</td>
    <% end %>
    <td>
    <a href="javascript:void(0);" onclick="update_house('<%=playground.id%>',true);" title=""><%= "Activate" %></a>
    |
    <a href="/playgrounds/<%=playground.id%>/edit" title=""><%='Edit'%></a>
    |
    <span title=""><%='Delete'%></span>
    </td>
	</tr>
<% end %>


</table>
<%= will_paginate @deleted_playgrounds %>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
        
        
       

       

</body>
</html>





<script>
function update_house(id,status){
	$.ajax({
    type: "get",
    url: "/playgrounds/update_house_status",
    data: {
    "id": id,
    "status": status
    },
    dataType : 'script',
    iframe: 'true',
    cache: false,
    success: function(data){
    }
    });

}

function update_location(lat,log,p_id){



$.ajax({
    type: "get",
    url: "/playgrounds",
    data: {
    "lat": lat,
    "log": log,
    "id":p_id
    },
    dataType : 'script',
    iframe: 'true',
    cache: false,
    success: function(data){
    }
    });
    
    // Invoke it
    // createMarkerWithInfoWindow();
}

</script>

app/views/playgrounds/authenticate_house_registration.js.erb
alert("fsdsgsgs")
Gmaps.map.visibleInfoWindow = new google.maps.InfoWindow({content: "dfd"});
    Gmaps.map.visibleInfoWindow.open(Gmaps.map.serviceObject, html_m);

app/views/playgrounds/create.js.erb
created_playground_id = undefined; // global js variable

<%if (@playground.errors.empty?) %>    
    
    var createMarkerWithInfoWindow = function () {
        created_playground_id = <%=@playground.id%>
        // Remove previous marker
        clearMarker(playgroundsNewMarker);

        // Create marker info
        var markerInfo = {    
            position: new google.maps.LatLng(
                    <%=@playground.latitude%>,
                    <%=@playground.longitude%>
            ), 
            map: Gmaps.map.serviceObject,
            id: <%=@playground.id%>
        }
            
        // Create new marker
        var marker = new google.maps.Marker(markerInfo);
    
        // Add marker serviceObject
        markerInfo.serviceObject = marker;
    
        // Add to the markers array
        Gmaps.map.markers.push(markerInfo);

        // On click open infowindow
        google.maps.event.addListener(marker, "click", function (e) {
            openInfowindow(
                "<%= j(render :template => 'playgrounds/show.html.erb', 
                              :locals  => { :playground => @playground}) %>", 
                marker
            )
        });
        
        // New pane content
        $("#contextual-panel").html("<%=j(render :partial => 'create_side') %>");
    
    
        // Notify user
        alert_user("Got it. A new playground has been added!","alert-info");
       
    }    
    
    // Invoke it
    createMarkerWithInfoWindow();
    

<%else%>
alert('<%=@playground.errors.full_messages.join(',')%>');
    // Notify user
    // alert_user("Aj Got :(... I can't insert that. <%= j(raw(@playground.errors.full_messages.join(','))) %>", "alert-error");

<%end%>


app/views/playgrounds/destroy.js.erb
// Clear the marker itself
// clearMarkerById(<%=@playground.id%>);

// Close infowindow
// closeInfowindow();

window.location.reload();

// Change the pane
// $("#contextual-panel").html( "<%=j(render :partial => 'destroy_side') %>");

// Notify
// alert_user("Destroyed a playground in tha neighborhood!", "alert-info");


app/views/playgrounds/edit.html.erb
<%= render 'edit_form' %>

app/views/playgrounds/edit.js.erb
// Open the edit form
openInfowindow(
    "<%= j(render :template => 'playgrounds/edit.html.erb', :locals  => {:playground => @playground}) %>", 
    findById(<%=@playground.id%>)
);           

app/views/playgrounds/new.html.erb
<%= render 'form' %>

app/views/playgrounds/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name & No:</strong> 
  <%= @playground.name %>
</p>
<p>
  <strong>Type:</strong> 
  <%= @playground.myadd_type %>
</p>


<p>
  <strong>Address:</strong> 
  <%= @playground.address %>
</p>
<p>
  <strong>City:</strong>
  <%= @playground.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @playground.state %>
</p>
<p>
  <strong>Country:</strong>
  <%= @playground.country %>
</p>
<p>
  <strong>Postal code:</strong>
  <%= @playground.postal_code %>
</p>
<p>
<strong>Address Bar:</strong>
  <b><%= @playground.address_bar_index %></b>
</p>
<p>
<strong>Image1:</strong>
  <b><%= image_tag @playground.logo.url(:small) if @playground && @playground.logo %></b>
</p>
<p>
<strong>Image2:</strong>
  <b><%= image_tag @playground.picture.url(:small) if @playground && @playground.picture %></b>
</p>

<%#= link_to 'Edit', edit_playground_path(@playground), class: "btn btn-lg btn-primary", :remote =>true  %>

<%#= link_to raw('Destroy <i class="icon-trash"></i>'), @playground, class: "btn btn-lg", method: "delete", data: { confirm: 'Are you sure?' }, :remote =>true %>
 
  <a href="javascript:void(0);" onclick="report_spam('<%=@playground.id%>','<%=@playground.latitude%>','<%=@playground.longitude%>');" class="btn btn-lg btn-primary"> Report Spam</a>
 


app/views/playgrounds/update.js.erb
<%if (@playground.errors.empty?) %>    

    var updateMarkerWithInfowindow = function () { 

        // Get marker
        var marker_to_update = findById(<%=@playground.id%>);

        // Newly updated infowindow behaviour
        var showUpdatedInfowinow = function() {
            openInfowindow(
                "<%= j(render :template => 'playgrounds/show.html.erb', 
                              :locals  => {:playground => @playground}) %>", 
                marker_to_update
            )
        };

        // Open the new window
        showUpdatedInfowinow();

        // Update click behaviour from now on to open this new infowindow
        google.maps.event.addListener(marker_to_update, "click", function (e) {
            showUpdatedInfowinow();
        });     
        
        // Change the pane
        $("#contextual-panel").html( "<%=j(render :partial => 'update_side') %>" );
    
        // Notify user    
        alert_user("Yap! You updated it correctly","alert-info");
    }
    
    // Invoke it
    updateMarkerWithInfowindow();  
      
<%else%>

    // Notify user
    alert_user("Errr, well, I could not update that. <%= j(raw(@playground.errors.full_messages.join(','))) %>","alert-error");

<%end%>